server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      # Comment out the routes section since we're using Java config
      # routes:
      #   - id: blockchain-route
      #     uri: lb://blockchain-service
      #     predicates:
      #       - Path=/blockchain/**
      #   - id: auth-route
      #     uri: lb://auth-service
      #     predicates:
      #       - Path=/auth/**
      httpclient:
        connect-timeout: 5000
        response-timeout: 5000

# JWT Configuration (must match the auth service)
jwt:
  secret: blockchain_microservice_security_key_must_be_very_long_and_secure

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix: DEBUG
    org.springframework.cloud.gateway.route: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud.gateway.filter: TRACE

# Eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 